name: deploy

on:
  push
  # the 1st condition
  # workflow_run:
  #   workflows: ["Publish Docker image API","Publish Docker image FRONTEND"]
  #   branches: [main]
  #   types:
  #     - completed

jobs:
  deploy-packages:
    name: dvc_repro execution
    # the 2nd condition
    # if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: 'just-a-placeholder-so-we-dont-get-errors'

      - name: Adding Known Hosts
        run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Pull and deploy on server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd glassdetection
            ls